version: '3'
services:
  user-manager:
    image: haiquanduan/user-manager:latest
    container_name: user-manager
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
      - 8000:8000
    networks:
      - "net"
  db:
    image: mysql:5.7
    container_name: db-mysql
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_USER: user_manager
      MYSQL_PASSWORD: "1qazCDE#"
      MYSQL_ROOT_PASSWORD: "1qazCDE#"
      MYSQL_DATABASE: "user_manager"
    ports:
      - 3306:3306
    networks:
      - "net"
    volumes:
      - /opt/mysql/:/var/lib/mysql/
networks:
  net:
    driver: bridge
